### ISSUE TITLE
Refresh on Place Changed Event

### ISSUE THREAD

**Issue by spencerfinnell** [FacetWP/facetwp-proximity#2]
When the `place_changed` event is fired I think `FWP.refresh();` should be called. For instance on Listify if they use only one facet then direct to another page with results the URL will never have updated if they only choose a suggestion from the autocomplete list.

**Comment by mgibbs189** [comment]
Oh gosh, I totally didn't see this :-s

**Comment by mgibbs189** [comment]
The reason it doesn't automatically refresh is because some users want to be able to set the Radius before a refresh is triggered (hence the Update button). I'm still on the fence about this though

![](http://i.imgur.com/YWM0BEg.png)

**Comment by spencerfinnell** [comment]
Yeah makes sense. I added it when used on the homepage on Listify where the radius option isn't shown yet.

**Comment by mgibbs189** [comment]
Fixed in latest version
